### ISSUE TITLE
How did you comeup with index.csv ?

### ISSUE THREAD

**Issue by SundeepPidugu** [rahulguptakota/paper-To-Reviewer-Matching-System#1]
I was able to generate text and get the xsml files for a publication but now i want to understand how you people came up with the index for the Paper,Cited-by ? and is there any API-source to get all the [ cited by ] for a research paper ? i was using google scholar but i was most of the referred papers are paid over there, is there an alternative method of doing this ?

**Comment by rahulguptakota** [comment]
As mentioned in Report, it was obtained from an existing dataset which identifies Meaningful citations.

**Comment by SundeepPidugu** [comment]
Is there any source to where i can pass a set of paper codes and it will automatically generate all of them ?

**Comment by rahulguptakota** [comment]
As I said before, the data is taken from http://ai2-website.s3.amazonaws.com/data/MeaningfulCitationsDataset.zip. For the rest, you can write helper scripts.
